source ./activate
cd filesys
make
cd build
make tests/filesys/buffer-cache/bc-easy.result 
make tests/filesys/extended/dir-empty-name-persistence.result 
make tests/filesys/extended/dir-mk-tree-persistence.result 
make tests/filesys/extended/dir-mkdir-persistence.result 
make tests/filesys/extended/dir-open-persistence.result 
make tests/filesys/extended/dir-over-file-persistence.result 
make tests/filesys/extended/dir-rm-cwd-persistence.result 
make tests/filesys/extended/dir-rm-parent-persistence.result 
make tests/filesys/extended/dir-rm-root-persistence.result 
make tests/filesys/extended/dir-rm-tree-persistence.result 
make tests/filesys/extended/dir-rmdir-persistence.result 
make tests/filesys/extended/dir-under-file-persistence.result 
make tests/filesys/extended/dir-vine-persistence.result 
make tests/filesys/extended/grow-create-persistence.result 
make tests/filesys/extended/grow-dir-lg-persistence.result 
make tests/filesys/extended/grow-file-size-persistence.result 
make tests/filesys/extended/grow-root-lg-persistence.result 
make tests/filesys/extended/grow-root-sm-persistence.result 
make tests/filesys/extended/grow-seq-lg-persistence.result 
make tests/filesys/extended/grow-seq-sm-persistence.result 
make tests/filesys/extended/grow-sparse-persistence.result 
make tests/filesys/extended/grow-tell-persistence.result 
make tests/filesys/extended/grow-two-files-persistence.result 
make tests/filesys/extended/syn-rw-persistence.result 
make tests/filesys/extended/symlink-file-persistence.result 
make tests/filesys/extended/symlink-dir-persistence.result 
make tests/filesys/extended/symlink-link-persistence
